/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./components/about/AboutPage.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeFooter: typeof import('./components/home/HomeFooter.vue')['default']
    HomeHeader: typeof import('./components/home/HomeHeader.vue')['default']
    HomePage: typeof import('./components/home/HomePage.vue')['default']
    PrivacyPolicyPage: typeof import('./components/privacy/PrivacyPolicyPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
