/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/landing/': RouteRecordInfo<'/landing/', '/landing', Record<never, never>, Record<never, never>>,
    '/landing/about/': RouteRecordInfo<'/landing/about/', '/landing/about', Record<never, never>, Record<never, never>>,
    '/landing/app': RouteRecordInfo<'/landing/app', '/landing/app', Record<never, never>, Record<never, never>>,
    '/landing/blogs/': RouteRecordInfo<'/landing/blogs/', '/landing/blogs', Record<never, never>, Record<never, never>>,
    '/landing/blogs/article/[id]': RouteRecordInfo<'/landing/blogs/article/[id]', '/landing/blogs/article/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/landing/branding/': RouteRecordInfo<'/landing/branding/', '/landing/branding', Record<never, never>, Record<never, never>>,
    '/landing/contact/': RouteRecordInfo<'/landing/contact/', '/landing/contact', Record<never, never>, Record<never, never>>,
    '/landing/forums/': RouteRecordInfo<'/landing/forums/', '/landing/forums', Record<never, never>, Record<never, never>>,
    '/landing/forums/category/[id]': RouteRecordInfo<'/landing/forums/category/[id]', '/landing/forums/category/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/landing/forums/thread/[id]': RouteRecordInfo<'/landing/forums/thread/[id]', '/landing/forums/thread/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/landing/home/': RouteRecordInfo<'/landing/home/', '/landing/home', Record<never, never>, Record<never, never>>,
    '/landing/login/': RouteRecordInfo<'/landing/login/', '/landing/login', Record<never, never>, Record<never, never>>,
    '/landing/missions/': RouteRecordInfo<'/landing/missions/', '/landing/missions', Record<never, never>, Record<never, never>>,
    '/landing/pricing/': RouteRecordInfo<'/landing/pricing/', '/landing/pricing', Record<never, never>, Record<never, never>>,
    '/landing/privacy/': RouteRecordInfo<'/landing/privacy/', '/landing/privacy', Record<never, never>, Record<never, never>>,
    '/landing/register/': RouteRecordInfo<'/landing/register/', '/landing/register', Record<never, never>, Record<never, never>>,
    '/landing/teams/': RouteRecordInfo<'/landing/teams/', '/landing/teams', Record<never, never>, Record<never, never>>,
    '/landing/terms/': RouteRecordInfo<'/landing/terms/', '/landing/terms', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/landing/index.vue': {
      routes: '/landing/'
      views: never
    }
    'src/pages/landing/about/index.vue': {
      routes: '/landing/about/'
      views: never
    }
    'src/pages/landing/app.vue': {
      routes: '/landing/app'
      views: never
    }
    'src/pages/landing/blogs/index.vue': {
      routes: '/landing/blogs/'
      views: never
    }
    'src/pages/landing/blogs/article/[id].vue': {
      routes: '/landing/blogs/article/[id]'
      views: never
    }
    'src/pages/landing/branding/index.vue': {
      routes: '/landing/branding/'
      views: never
    }
    'src/pages/landing/contact/index.vue': {
      routes: '/landing/contact/'
      views: never
    }
    'src/pages/landing/forums/index.vue': {
      routes: '/landing/forums/'
      views: never
    }
    'src/pages/landing/forums/category/[id].vue': {
      routes: '/landing/forums/category/[id]'
      views: never
    }
    'src/pages/landing/forums/thread/[id].vue': {
      routes: '/landing/forums/thread/[id]'
      views: never
    }
    'src/pages/landing/home/index.vue': {
      routes: '/landing/home/'
      views: never
    }
    'src/pages/landing/login/index.vue': {
      routes: '/landing/login/'
      views: never
    }
    'src/pages/landing/missions/index.vue': {
      routes: '/landing/missions/'
      views: never
    }
    'src/pages/landing/pricing/index.vue': {
      routes: '/landing/pricing/'
      views: never
    }
    'src/pages/landing/privacy/index.vue': {
      routes: '/landing/privacy/'
      views: never
    }
    'src/pages/landing/register/index.vue': {
      routes: '/landing/register/'
      views: never
    }
    'src/pages/landing/teams/index.vue': {
      routes: '/landing/teams/'
      views: never
    }
    'src/pages/landing/terms/index.vue': {
      routes: '/landing/terms/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
